/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as ErrorServerRouteImport } from './routes/error-server'
import { Route as LupaSandiRouteImport } from './routes/lupa-sandi'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as PerawatanRouteImport } from './routes/perawatan'
import { Route as ResetSandiRouteImport } from './routes/reset-sandi'
import { Route as VerifikasiEmailRouteImport } from './routes/verifikasi-email'
import { Route as AppBelajarRouteImport } from './routes/_app.belajar'
import { Route as AppBerandaRouteImport } from './routes/_app.beranda'
import { Route as AppCariRouteImport } from './routes/_app.cari'
import { Route as AppGambarRouteImport } from './routes/_app.gambar'
import { Route as AppGlosariumRouteImport } from './routes/_app.glosarium'
import { Route as AppKalenderRouteImport } from './routes/_app.kalender'
import { Route as AppKartuRouteImport } from './routes/_app.kartu'
import { Route as AppKuisRouteImport } from './routes/_app.kuis'
import { Route as AppMindmapRouteImport } from './routes/_app.mindmap'
import { Route as AppNotifikasiRouteImport } from './routes/_app.notifikasi'
import { Route as AppPencapaianRouteImport } from './routes/_app.pencapaian'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppPeringkatRouteImport } from './routes/_app.peringkat'
import { Route as AppPomodoroRouteImport } from './routes/_app.pomodoro'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppProgresRouteImport } from './routes/_app.progres'
import { Route as AppReferensiRouteImport } from './routes/_app.referensi'
import { Route as AppRencanaRouteImport } from './routes/_app.rencana'
import { Route as AppRiwayatRouteImport } from './routes/_app.riwayat'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppSertifikatRouteImport } from './routes/_app.sertifikat'
import { Route as AppSorotanRouteImport } from './routes/_app.sorotan'
import { Route as AppStudiKasusRouteImport } from './routes/_app.studi-kasus'
import { Route as AppTersimpanRouteImport } from './routes/_app.tersimpan'
import { Route as AppUnduhanRouteImport } from './routes/_app.unduhan'
import { Route as AppVisualRouteImport } from './routes/_app.visual'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'
import { Route as AppAdminGambarRouteImport } from './routes/_app.admin.gambar'
import { Route as AppAdminGlosariumRouteImport } from './routes/_app.admin.glosarium'
import { Route as AppAdminKeyRouteImport } from './routes/_app.admin.key'
import { Route as AppAdminPengaturanRouteImport } from './routes/_app.admin.pengaturan'
import { Route as AppAdminPenggunaRouteImport } from './routes/_app.admin.pengguna'
import { Route as AppAdminProfilRouteImport } from './routes/_app.admin.profil'
import { Route as AppAdminReferensiRouteImport } from './routes/_app.admin.referensi'
import { Route as AppAiCatatanRouteImport } from './routes/_app.ai.catatan'
import { Route as AppAiChatRouteImport } from './routes/_app.ai.chat'
import { Route as AppAiJelaskanRouteImport } from './routes/_app.ai.jelaskan'
import { Route as AppAiRiwayatRouteImport } from './routes/_app.ai.riwayat'
import { Route as AppBelajarMateriRouteImport } from './routes/_app.belajar.materi'
import { Route as AppKuisSlugRouteImport } from './routes/_app.kuis.$slug'
import { Route as AppKuisHasilRouteImport } from './routes/_app.kuis.hasil'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAdminKuisIndexRouteImport } from './routes/_app.admin.kuis.index'
import { Route as AppAdminKuisIdRouteImport } from './routes/_app.admin.kuis.$id'
import { Route as AppAdminKuisBaruRouteImport } from './routes/_app.admin.kuis.baru'
import { Route as AppAdminMateriIndexRouteImport } from './routes/_app.admin.materi.index'
import { Route as AppAdminMateriSlugRouteImport } from './routes/_app.admin.materi.$slug'
import { Route as AppAdminModulIndexRouteImport } from './routes/_app.admin.modul.index'
import { Route as AppAdminModulSlugRouteImport } from './routes/_app.admin.modul.$slug'
import { Route as AppAdminModulBaruRouteImport } from './routes/_app.admin.modul.baru'
import { Route as AppAdminPromptStudioIndexRouteImport } from './routes/_app.admin.prompt-studio.index'
import { Route as AppAdminPromptStudioCompilerRouteImport } from './routes/_app.admin.prompt-studio.compiler'
import { Route as AppAdminStudiKasusIndexRouteImport } from './routes/_app.admin.studi-kasus.index'
import { Route as AppAdminStudiKasusIdRouteImport } from './routes/_app.admin.studi-kasus.$id'
import { Route as AppAdminStudiKasusBaruRouteImport } from './routes/_app.admin.studi-kasus.baru'
import { Route as AppAiChatIdRouteImport } from './routes/_app.ai.chat.$id'
import { Route as AppBelajarMateriSlugRouteImport } from './routes/_app.belajar.materi.$slug'
import { Route as AppRoadmapMateriSlugRouteImport } from './routes/_app.roadmap.materi.$slug'
import { Route as AppAdminPromptStudioEngineIdRouteImport } from './routes/_app.admin.prompt-studio.engine.$id'
import { Route as AppBelajarMateriSlugQuizRouteImport } from './routes/_app.belajar.materi.$slug.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorServerRoute = ErrorServerRouteImport.update({
  id: '/error-server',
  path: '/error-server',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaSandiRoute = LupaSandiRouteImport.update({
  id: '/lupa-sandi',
  path: '/lupa-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const PerawatanRoute = PerawatanRouteImport.update({
  id: '/perawatan',
  path: '/perawatan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSandiRoute = ResetSandiRouteImport.update({
  id: '/reset-sandi',
  path: '/reset-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiEmailRoute = VerifikasiEmailRouteImport.update({
  id: '/verifikasi-email',
  path: '/verifikasi-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBelajarRoute = AppBelajarRouteImport.update({
  id: '/belajar',
  path: '/belajar',
  getParentRoute: () => AppRoute,
} as any)
const AppBerandaRoute = AppBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AppRoute,
} as any)
const AppCariRoute = AppCariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => AppRoute,
} as any)
const AppGambarRoute = AppGambarRouteImport.update({
  id: '/gambar',
  path: '/gambar',
  getParentRoute: () => AppRoute,
} as any)
const AppGlosariumRoute = AppGlosariumRouteImport.update({
  id: '/glosarium',
  path: '/glosarium',
  getParentRoute: () => AppRoute,
} as any)
const AppKalenderRoute = AppKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AppRoute,
} as any)
const AppKartuRoute = AppKartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => AppRoute,
} as any)
const AppKuisRoute = AppKuisRouteImport.update({
  id: '/kuis',
  path: '/kuis',
  getParentRoute: () => AppRoute,
} as any)
const AppMindmapRoute = AppMindmapRouteImport.update({
  id: '/mindmap',
  path: '/mindmap',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifikasiRoute = AppNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppPencapaianRoute = AppPencapaianRouteImport.update({
  id: '/pencapaian',
  path: '/pencapaian',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPeringkatRoute = AppPeringkatRouteImport.update({
  id: '/peringkat',
  path: '/peringkat',
  getParentRoute: () => AppRoute,
} as any)
const AppPomodoroRoute = AppPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresRoute = AppProgresRouteImport.update({
  id: '/progres',
  path: '/progres',
  getParentRoute: () => AppRoute,
} as any)
const AppReferensiRoute = AppReferensiRouteImport.update({
  id: '/referensi',
  path: '/referensi',
  getParentRoute: () => AppRoute,
} as any)
const AppRencanaRoute = AppRencanaRouteImport.update({
  id: '/rencana',
  path: '/rencana',
  getParentRoute: () => AppRoute,
} as any)
const AppRiwayatRoute = AppRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppSertifikatRoute = AppSertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => AppRoute,
} as any)
const AppSorotanRoute = AppSorotanRouteImport.update({
  id: '/sorotan',
  path: '/sorotan',
  getParentRoute: () => AppRoute,
} as any)
const AppStudiKasusRoute = AppStudiKasusRouteImport.update({
  id: '/studi-kasus',
  path: '/studi-kasus',
  getParentRoute: () => AppRoute,
} as any)
const AppTersimpanRoute = AppTersimpanRouteImport.update({
  id: '/tersimpan',
  path: '/tersimpan',
  getParentRoute: () => AppRoute,
} as any)
const AppUnduhanRoute = AppUnduhanRouteImport.update({
  id: '/unduhan',
  path: '/unduhan',
  getParentRoute: () => AppRoute,
} as any)
const AppVisualRoute = AppVisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGambarRoute = AppAdminGambarRouteImport.update({
  id: '/admin/gambar',
  path: '/admin/gambar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminGlosariumRoute = AppAdminGlosariumRouteImport.update({
  id: '/admin/glosarium',
  path: '/admin/glosarium',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminKeyRoute = AppAdminKeyRouteImport.update({
  id: '/admin/key',
  path: '/admin/key',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPengaturanRoute = AppAdminPengaturanRouteImport.update({
  id: '/admin/pengaturan',
  path: '/admin/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPenggunaRoute = AppAdminPenggunaRouteImport.update({
  id: '/admin/pengguna',
  path: '/admin/pengguna',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProfilRoute = AppAdminProfilRouteImport.update({
  id: '/admin/profil',
  path: '/admin/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReferensiRoute = AppAdminReferensiRouteImport.update({
  id: '/admin/referensi',
  path: '/admin/referensi',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCatatanRoute = AppAiCatatanRouteImport.update({
  id: '/ai/catatan',
  path: '/ai/catatan',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAiJelaskanRoute = AppAiJelaskanRouteImport.update({
  id: '/ai/jelaskan',
  path: '/ai/jelaskan',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRiwayatRoute = AppAiRiwayatRouteImport.update({
  id: '/ai/riwayat',
  path: '/ai/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppBelajarMateriRoute = AppBelajarMateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => AppBelajarRoute,
} as any)
const AppKuisSlugRoute = AppKuisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppKuisRoute,
} as any)
const AppKuisHasilRoute = AppKuisHasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => AppKuisRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminKuisIndexRoute = AppAdminKuisIndexRouteImport.update({
  id: '/admin/kuis/',
  path: '/admin/kuis/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminKuisIdRoute = AppAdminKuisIdRouteImport.update({
  id: '/admin/kuis/$id',
  path: '/admin/kuis/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminKuisBaruRoute = AppAdminKuisBaruRouteImport.update({
  id: '/admin/kuis/baru',
  path: '/admin/kuis/baru',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMateriIndexRoute = AppAdminMateriIndexRouteImport.update({
  id: '/admin/materi/',
  path: '/admin/materi/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMateriSlugRoute = AppAdminMateriSlugRouteImport.update({
  id: '/admin/materi/$slug',
  path: '/admin/materi/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminModulIndexRoute = AppAdminModulIndexRouteImport.update({
  id: '/admin/modul/',
  path: '/admin/modul/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminModulSlugRoute = AppAdminModulSlugRouteImport.update({
  id: '/admin/modul/$slug',
  path: '/admin/modul/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminModulBaruRoute = AppAdminModulBaruRouteImport.update({
  id: '/admin/modul/baru',
  path: '/admin/modul/baru',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPromptStudioIndexRoute =
  AppAdminPromptStudioIndexRouteImport.update({
    id: '/admin/prompt-studio/',
    path: '/admin/prompt-studio/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminPromptStudioCompilerRoute =
  AppAdminPromptStudioCompilerRouteImport.update({
    id: '/admin/prompt-studio/compiler',
    path: '/admin/prompt-studio/compiler',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminStudiKasusIndexRoute = AppAdminStudiKasusIndexRouteImport.update({
  id: '/admin/studi-kasus/',
  path: '/admin/studi-kasus/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStudiKasusIdRoute = AppAdminStudiKasusIdRouteImport.update({
  id: '/admin/studi-kasus/$id',
  path: '/admin/studi-kasus/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStudiKasusBaruRoute = AppAdminStudiKasusBaruRouteImport.update({
  id: '/admin/studi-kasus/baru',
  path: '/admin/studi-kasus/baru',
  getParentRoute: () => AppRoute,
} as any)
const AppAiChatIdRoute = AppAiChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAiChatRoute,
} as any)
const AppBelajarMateriSlugRoute = AppBelajarMateriSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppBelajarMateriRoute,
} as any)
const AppRoadmapMateriSlugRoute = AppRoadmapMateriSlugRouteImport.update({
  id: '/materi/$slug',
  path: '/materi/$slug',
  getParentRoute: () => AppRoadmapRoute,
} as any)
const AppAdminPromptStudioEngineIdRoute =
  AppAdminPromptStudioEngineIdRouteImport.update({
    id: '/admin/prompt-studio/engine/$id',
    path: '/admin/prompt-studio/engine/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppBelajarMateriSlugQuizRoute =
  AppBelajarMateriSlugQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AppBelajarMateriSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/error-server': typeof ErrorServerRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/masuk': typeof MasukRoute
  '/perawatan': typeof PerawatanRoute
  '/reset-sandi': typeof ResetSandiRoute
  '/verifikasi-email': typeof VerifikasiEmailRoute
  '/belajar': typeof AppBelajarRouteWithChildren
  '/beranda': typeof AppBerandaRoute
  '/cari': typeof AppCariRoute
  '/gambar': typeof AppGambarRoute
  '/glosarium': typeof AppGlosariumRoute
  '/kalender': typeof AppKalenderRoute
  '/kartu': typeof AppKartuRoute
  '/kuis': typeof AppKuisRouteWithChildren
  '/mindmap': typeof AppMindmapRoute
  '/notifikasi': typeof AppNotifikasiRoute
  '/pencapaian': typeof AppPencapaianRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/peringkat': typeof AppPeringkatRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profil': typeof AppProfilRoute
  '/progres': typeof AppProgresRoute
  '/referensi': typeof AppReferensiRoute
  '/rencana': typeof AppRencanaRoute
  '/riwayat': typeof AppRiwayatRoute
  '/roadmap': typeof AppRoadmapRouteWithChildren
  '/sertifikat': typeof AppSertifikatRoute
  '/sorotan': typeof AppSorotanRoute
  '/studi-kasus': typeof AppStudiKasusRoute
  '/tersimpan': typeof AppTersimpanRoute
  '/unduhan': typeof AppUnduhanRoute
  '/visual': typeof AppVisualRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/gambar': typeof AppAdminGambarRoute
  '/admin/glosarium': typeof AppAdminGlosariumRoute
  '/admin/key': typeof AppAdminKeyRoute
  '/admin/pengaturan': typeof AppAdminPengaturanRoute
  '/admin/pengguna': typeof AppAdminPenggunaRoute
  '/admin/profil': typeof AppAdminProfilRoute
  '/admin/referensi': typeof AppAdminReferensiRoute
  '/ai/catatan': typeof AppAiCatatanRoute
  '/ai/chat': typeof AppAiChatRouteWithChildren
  '/ai/jelaskan': typeof AppAiJelaskanRoute
  '/ai/riwayat': typeof AppAiRiwayatRoute
  '/belajar/materi': typeof AppBelajarMateriRouteWithChildren
  '/kuis/$slug': typeof AppKuisSlugRoute
  '/kuis/hasil': typeof AppKuisHasilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/kuis/$id': typeof AppAdminKuisIdRoute
  '/admin/kuis/baru': typeof AppAdminKuisBaruRoute
  '/admin/materi/$slug': typeof AppAdminMateriSlugRoute
  '/admin/modul/$slug': typeof AppAdminModulSlugRoute
  '/admin/modul/baru': typeof AppAdminModulBaruRoute
  '/admin/prompt-studio/compiler': typeof AppAdminPromptStudioCompilerRoute
  '/admin/studi-kasus/$id': typeof AppAdminStudiKasusIdRoute
  '/admin/studi-kasus/baru': typeof AppAdminStudiKasusBaruRoute
  '/ai/chat/$id': typeof AppAiChatIdRoute
  '/belajar/materi/$slug': typeof AppBelajarMateriSlugRouteWithChildren
  '/roadmap/materi/$slug': typeof AppRoadmapMateriSlugRoute
  '/admin/kuis/': typeof AppAdminKuisIndexRoute
  '/admin/materi/': typeof AppAdminMateriIndexRoute
  '/admin/modul/': typeof AppAdminModulIndexRoute
  '/admin/prompt-studio/': typeof AppAdminPromptStudioIndexRoute
  '/admin/studi-kasus/': typeof AppAdminStudiKasusIndexRoute
  '/admin/prompt-studio/engine/$id': typeof AppAdminPromptStudioEngineIdRoute
  '/belajar/materi/$slug/quiz': typeof AppBelajarMateriSlugQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/error-server': typeof ErrorServerRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/masuk': typeof MasukRoute
  '/perawatan': typeof PerawatanRoute
  '/reset-sandi': typeof ResetSandiRoute
  '/verifikasi-email': typeof VerifikasiEmailRoute
  '/belajar': typeof AppBelajarRouteWithChildren
  '/beranda': typeof AppBerandaRoute
  '/cari': typeof AppCariRoute
  '/gambar': typeof AppGambarRoute
  '/glosarium': typeof AppGlosariumRoute
  '/kalender': typeof AppKalenderRoute
  '/kartu': typeof AppKartuRoute
  '/kuis': typeof AppKuisRouteWithChildren
  '/mindmap': typeof AppMindmapRoute
  '/notifikasi': typeof AppNotifikasiRoute
  '/pencapaian': typeof AppPencapaianRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/peringkat': typeof AppPeringkatRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profil': typeof AppProfilRoute
  '/progres': typeof AppProgresRoute
  '/referensi': typeof AppReferensiRoute
  '/rencana': typeof AppRencanaRoute
  '/riwayat': typeof AppRiwayatRoute
  '/roadmap': typeof AppRoadmapRouteWithChildren
  '/sertifikat': typeof AppSertifikatRoute
  '/sorotan': typeof AppSorotanRoute
  '/studi-kasus': typeof AppStudiKasusRoute
  '/tersimpan': typeof AppTersimpanRoute
  '/unduhan': typeof AppUnduhanRoute
  '/visual': typeof AppVisualRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/gambar': typeof AppAdminGambarRoute
  '/admin/glosarium': typeof AppAdminGlosariumRoute
  '/admin/key': typeof AppAdminKeyRoute
  '/admin/pengaturan': typeof AppAdminPengaturanRoute
  '/admin/pengguna': typeof AppAdminPenggunaRoute
  '/admin/profil': typeof AppAdminProfilRoute
  '/admin/referensi': typeof AppAdminReferensiRoute
  '/ai/catatan': typeof AppAiCatatanRoute
  '/ai/chat': typeof AppAiChatRouteWithChildren
  '/ai/jelaskan': typeof AppAiJelaskanRoute
  '/ai/riwayat': typeof AppAiRiwayatRoute
  '/belajar/materi': typeof AppBelajarMateriRouteWithChildren
  '/kuis/$slug': typeof AppKuisSlugRoute
  '/kuis/hasil': typeof AppKuisHasilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/kuis/$id': typeof AppAdminKuisIdRoute
  '/admin/kuis/baru': typeof AppAdminKuisBaruRoute
  '/admin/materi/$slug': typeof AppAdminMateriSlugRoute
  '/admin/modul/$slug': typeof AppAdminModulSlugRoute
  '/admin/modul/baru': typeof AppAdminModulBaruRoute
  '/admin/prompt-studio/compiler': typeof AppAdminPromptStudioCompilerRoute
  '/admin/studi-kasus/$id': typeof AppAdminStudiKasusIdRoute
  '/admin/studi-kasus/baru': typeof AppAdminStudiKasusBaruRoute
  '/ai/chat/$id': typeof AppAiChatIdRoute
  '/belajar/materi/$slug': typeof AppBelajarMateriSlugRouteWithChildren
  '/roadmap/materi/$slug': typeof AppRoadmapMateriSlugRoute
  '/admin/kuis': typeof AppAdminKuisIndexRoute
  '/admin/materi': typeof AppAdminMateriIndexRoute
  '/admin/modul': typeof AppAdminModulIndexRoute
  '/admin/prompt-studio': typeof AppAdminPromptStudioIndexRoute
  '/admin/studi-kasus': typeof AppAdminStudiKasusIndexRoute
  '/admin/prompt-studio/engine/$id': typeof AppAdminPromptStudioEngineIdRoute
  '/belajar/materi/$slug/quiz': typeof AppBelajarMateriSlugQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/error-server': typeof ErrorServerRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/masuk': typeof MasukRoute
  '/perawatan': typeof PerawatanRoute
  '/reset-sandi': typeof ResetSandiRoute
  '/verifikasi-email': typeof VerifikasiEmailRoute
  '/_app/belajar': typeof AppBelajarRouteWithChildren
  '/_app/beranda': typeof AppBerandaRoute
  '/_app/cari': typeof AppCariRoute
  '/_app/gambar': typeof AppGambarRoute
  '/_app/glosarium': typeof AppGlosariumRoute
  '/_app/kalender': typeof AppKalenderRoute
  '/_app/kartu': typeof AppKartuRoute
  '/_app/kuis': typeof AppKuisRouteWithChildren
  '/_app/mindmap': typeof AppMindmapRoute
  '/_app/notifikasi': typeof AppNotifikasiRoute
  '/_app/pencapaian': typeof AppPencapaianRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/peringkat': typeof AppPeringkatRoute
  '/_app/pomodoro': typeof AppPomodoroRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/progres': typeof AppProgresRoute
  '/_app/referensi': typeof AppReferensiRoute
  '/_app/rencana': typeof AppRencanaRoute
  '/_app/riwayat': typeof AppRiwayatRoute
  '/_app/roadmap': typeof AppRoadmapRouteWithChildren
  '/_app/sertifikat': typeof AppSertifikatRoute
  '/_app/sorotan': typeof AppSorotanRoute
  '/_app/studi-kasus': typeof AppStudiKasusRoute
  '/_app/tersimpan': typeof AppTersimpanRoute
  '/_app/unduhan': typeof AppUnduhanRoute
  '/_app/visual': typeof AppVisualRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/gambar': typeof AppAdminGambarRoute
  '/_app/admin/glosarium': typeof AppAdminGlosariumRoute
  '/_app/admin/key': typeof AppAdminKeyRoute
  '/_app/admin/pengaturan': typeof AppAdminPengaturanRoute
  '/_app/admin/pengguna': typeof AppAdminPenggunaRoute
  '/_app/admin/profil': typeof AppAdminProfilRoute
  '/_app/admin/referensi': typeof AppAdminReferensiRoute
  '/_app/ai/catatan': typeof AppAiCatatanRoute
  '/_app/ai/chat': typeof AppAiChatRouteWithChildren
  '/_app/ai/jelaskan': typeof AppAiJelaskanRoute
  '/_app/ai/riwayat': typeof AppAiRiwayatRoute
  '/_app/belajar/materi': typeof AppBelajarMateriRouteWithChildren
  '/_app/kuis/$slug': typeof AppKuisSlugRoute
  '/_app/kuis/hasil': typeof AppKuisHasilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/kuis/$id': typeof AppAdminKuisIdRoute
  '/_app/admin/kuis/baru': typeof AppAdminKuisBaruRoute
  '/_app/admin/materi/$slug': typeof AppAdminMateriSlugRoute
  '/_app/admin/modul/$slug': typeof AppAdminModulSlugRoute
  '/_app/admin/modul/baru': typeof AppAdminModulBaruRoute
  '/_app/admin/prompt-studio/compiler': typeof AppAdminPromptStudioCompilerRoute
  '/_app/admin/studi-kasus/$id': typeof AppAdminStudiKasusIdRoute
  '/_app/admin/studi-kasus/baru': typeof AppAdminStudiKasusBaruRoute
  '/_app/ai/chat/$id': typeof AppAiChatIdRoute
  '/_app/belajar/materi/$slug': typeof AppBelajarMateriSlugRouteWithChildren
  '/_app/roadmap/materi/$slug': typeof AppRoadmapMateriSlugRoute
  '/_app/admin/kuis/': typeof AppAdminKuisIndexRoute
  '/_app/admin/materi/': typeof AppAdminMateriIndexRoute
  '/_app/admin/modul/': typeof AppAdminModulIndexRoute
  '/_app/admin/prompt-studio/': typeof AppAdminPromptStudioIndexRoute
  '/_app/admin/studi-kasus/': typeof AppAdminStudiKasusIndexRoute
  '/_app/admin/prompt-studio/engine/$id': typeof AppAdminPromptStudioEngineIdRoute
  '/_app/belajar/materi/$slug/quiz': typeof AppBelajarMateriSlugQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/error-server'
    | '/lupa-sandi'
    | '/masuk'
    | '/perawatan'
    | '/reset-sandi'
    | '/verifikasi-email'
    | '/belajar'
    | '/beranda'
    | '/cari'
    | '/gambar'
    | '/glosarium'
    | '/kalender'
    | '/kartu'
    | '/kuis'
    | '/mindmap'
    | '/notifikasi'
    | '/pencapaian'
    | '/pengaturan'
    | '/peringkat'
    | '/pomodoro'
    | '/profil'
    | '/progres'
    | '/referensi'
    | '/rencana'
    | '/riwayat'
    | '/roadmap'
    | '/sertifikat'
    | '/sorotan'
    | '/studi-kasus'
    | '/tersimpan'
    | '/unduhan'
    | '/visual'
    | '/admin/dashboard'
    | '/admin/gambar'
    | '/admin/glosarium'
    | '/admin/key'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/profil'
    | '/admin/referensi'
    | '/ai/catatan'
    | '/ai/chat'
    | '/ai/jelaskan'
    | '/ai/riwayat'
    | '/belajar/materi'
    | '/kuis/$slug'
    | '/kuis/hasil'
    | '/api/auth/$'
    | '/admin/'
    | '/admin/kuis/$id'
    | '/admin/kuis/baru'
    | '/admin/materi/$slug'
    | '/admin/modul/$slug'
    | '/admin/modul/baru'
    | '/admin/prompt-studio/compiler'
    | '/admin/studi-kasus/$id'
    | '/admin/studi-kasus/baru'
    | '/ai/chat/$id'
    | '/belajar/materi/$slug'
    | '/roadmap/materi/$slug'
    | '/admin/kuis/'
    | '/admin/materi/'
    | '/admin/modul/'
    | '/admin/prompt-studio/'
    | '/admin/studi-kasus/'
    | '/admin/prompt-studio/engine/$id'
    | '/belajar/materi/$slug/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/error-server'
    | '/lupa-sandi'
    | '/masuk'
    | '/perawatan'
    | '/reset-sandi'
    | '/verifikasi-email'
    | '/belajar'
    | '/beranda'
    | '/cari'
    | '/gambar'
    | '/glosarium'
    | '/kalender'
    | '/kartu'
    | '/kuis'
    | '/mindmap'
    | '/notifikasi'
    | '/pencapaian'
    | '/pengaturan'
    | '/peringkat'
    | '/pomodoro'
    | '/profil'
    | '/progres'
    | '/referensi'
    | '/rencana'
    | '/riwayat'
    | '/roadmap'
    | '/sertifikat'
    | '/sorotan'
    | '/studi-kasus'
    | '/tersimpan'
    | '/unduhan'
    | '/visual'
    | '/admin/dashboard'
    | '/admin/gambar'
    | '/admin/glosarium'
    | '/admin/key'
    | '/admin/pengaturan'
    | '/admin/pengguna'
    | '/admin/profil'
    | '/admin/referensi'
    | '/ai/catatan'
    | '/ai/chat'
    | '/ai/jelaskan'
    | '/ai/riwayat'
    | '/belajar/materi'
    | '/kuis/$slug'
    | '/kuis/hasil'
    | '/api/auth/$'
    | '/admin'
    | '/admin/kuis/$id'
    | '/admin/kuis/baru'
    | '/admin/materi/$slug'
    | '/admin/modul/$slug'
    | '/admin/modul/baru'
    | '/admin/prompt-studio/compiler'
    | '/admin/studi-kasus/$id'
    | '/admin/studi-kasus/baru'
    | '/ai/chat/$id'
    | '/belajar/materi/$slug'
    | '/roadmap/materi/$slug'
    | '/admin/kuis'
    | '/admin/materi'
    | '/admin/modul'
    | '/admin/prompt-studio'
    | '/admin/studi-kasus'
    | '/admin/prompt-studio/engine/$id'
    | '/belajar/materi/$slug/quiz'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/daftar'
    | '/error-server'
    | '/lupa-sandi'
    | '/masuk'
    | '/perawatan'
    | '/reset-sandi'
    | '/verifikasi-email'
    | '/_app/belajar'
    | '/_app/beranda'
    | '/_app/cari'
    | '/_app/gambar'
    | '/_app/glosarium'
    | '/_app/kalender'
    | '/_app/kartu'
    | '/_app/kuis'
    | '/_app/mindmap'
    | '/_app/notifikasi'
    | '/_app/pencapaian'
    | '/_app/pengaturan'
    | '/_app/peringkat'
    | '/_app/pomodoro'
    | '/_app/profil'
    | '/_app/progres'
    | '/_app/referensi'
    | '/_app/rencana'
    | '/_app/riwayat'
    | '/_app/roadmap'
    | '/_app/sertifikat'
    | '/_app/sorotan'
    | '/_app/studi-kasus'
    | '/_app/tersimpan'
    | '/_app/unduhan'
    | '/_app/visual'
    | '/_app/admin/dashboard'
    | '/_app/admin/gambar'
    | '/_app/admin/glosarium'
    | '/_app/admin/key'
    | '/_app/admin/pengaturan'
    | '/_app/admin/pengguna'
    | '/_app/admin/profil'
    | '/_app/admin/referensi'
    | '/_app/ai/catatan'
    | '/_app/ai/chat'
    | '/_app/ai/jelaskan'
    | '/_app/ai/riwayat'
    | '/_app/belajar/materi'
    | '/_app/kuis/$slug'
    | '/_app/kuis/hasil'
    | '/api/auth/$'
    | '/_app/admin/'
    | '/_app/admin/kuis/$id'
    | '/_app/admin/kuis/baru'
    | '/_app/admin/materi/$slug'
    | '/_app/admin/modul/$slug'
    | '/_app/admin/modul/baru'
    | '/_app/admin/prompt-studio/compiler'
    | '/_app/admin/studi-kasus/$id'
    | '/_app/admin/studi-kasus/baru'
    | '/_app/ai/chat/$id'
    | '/_app/belajar/materi/$slug'
    | '/_app/roadmap/materi/$slug'
    | '/_app/admin/kuis/'
    | '/_app/admin/materi/'
    | '/_app/admin/modul/'
    | '/_app/admin/prompt-studio/'
    | '/_app/admin/studi-kasus/'
    | '/_app/admin/prompt-studio/engine/$id'
    | '/_app/belajar/materi/$slug/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  ErrorServerRoute: typeof ErrorServerRoute
  LupaSandiRoute: typeof LupaSandiRoute
  MasukRoute: typeof MasukRoute
  PerawatanRoute: typeof PerawatanRoute
  ResetSandiRoute: typeof ResetSandiRoute
  VerifikasiEmailRoute: typeof VerifikasiEmailRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-server': {
      id: '/error-server'
      path: '/error-server'
      fullPath: '/error-server'
      preLoaderRoute: typeof ErrorServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-sandi': {
      id: '/lupa-sandi'
      path: '/lupa-sandi'
      fullPath: '/lupa-sandi'
      preLoaderRoute: typeof LupaSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perawatan': {
      id: '/perawatan'
      path: '/perawatan'
      fullPath: '/perawatan'
      preLoaderRoute: typeof PerawatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-sandi': {
      id: '/reset-sandi'
      path: '/reset-sandi'
      fullPath: '/reset-sandi'
      preLoaderRoute: typeof ResetSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi-email': {
      id: '/verifikasi-email'
      path: '/verifikasi-email'
      fullPath: '/verifikasi-email'
      preLoaderRoute: typeof VerifikasiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/belajar': {
      id: '/_app/belajar'
      path: '/belajar'
      fullPath: '/belajar'
      preLoaderRoute: typeof AppBelajarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beranda': {
      id: '/_app/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AppBerandaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cari': {
      id: '/_app/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof AppCariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gambar': {
      id: '/_app/gambar'
      path: '/gambar'
      fullPath: '/gambar'
      preLoaderRoute: typeof AppGambarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/glosarium': {
      id: '/_app/glosarium'
      path: '/glosarium'
      fullPath: '/glosarium'
      preLoaderRoute: typeof AppGlosariumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalender': {
      id: '/_app/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AppKalenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kartu': {
      id: '/_app/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof AppKartuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kuis': {
      id: '/_app/kuis'
      path: '/kuis'
      fullPath: '/kuis'
      preLoaderRoute: typeof AppKuisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mindmap': {
      id: '/_app/mindmap'
      path: '/mindmap'
      fullPath: '/mindmap'
      preLoaderRoute: typeof AppMindmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifikasi': {
      id: '/_app/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AppNotifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pencapaian': {
      id: '/_app/pencapaian'
      path: '/pencapaian'
      fullPath: '/pencapaian'
      preLoaderRoute: typeof AppPencapaianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/peringkat': {
      id: '/_app/peringkat'
      path: '/peringkat'
      fullPath: '/peringkat'
      preLoaderRoute: typeof AppPeringkatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pomodoro': {
      id: '/_app/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof AppPomodoroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progres': {
      id: '/_app/progres'
      path: '/progres'
      fullPath: '/progres'
      preLoaderRoute: typeof AppProgresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referensi': {
      id: '/_app/referensi'
      path: '/referensi'
      fullPath: '/referensi'
      preLoaderRoute: typeof AppReferensiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rencana': {
      id: '/_app/rencana'
      path: '/rencana'
      fullPath: '/rencana'
      preLoaderRoute: typeof AppRencanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riwayat': {
      id: '/_app/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AppRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sertifikat': {
      id: '/_app/sertifikat'
      path: '/sertifikat'
      fullPath: '/sertifikat'
      preLoaderRoute: typeof AppSertifikatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sorotan': {
      id: '/_app/sorotan'
      path: '/sorotan'
      fullPath: '/sorotan'
      preLoaderRoute: typeof AppSorotanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studi-kasus': {
      id: '/_app/studi-kasus'
      path: '/studi-kasus'
      fullPath: '/studi-kasus'
      preLoaderRoute: typeof AppStudiKasusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tersimpan': {
      id: '/_app/tersimpan'
      path: '/tersimpan'
      fullPath: '/tersimpan'
      preLoaderRoute: typeof AppTersimpanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unduhan': {
      id: '/_app/unduhan'
      path: '/unduhan'
      fullPath: '/unduhan'
      preLoaderRoute: typeof AppUnduhanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visual': {
      id: '/_app/visual'
      path: '/visual'
      fullPath: '/visual'
      preLoaderRoute: typeof AppVisualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/gambar': {
      id: '/_app/admin/gambar'
      path: '/admin/gambar'
      fullPath: '/admin/gambar'
      preLoaderRoute: typeof AppAdminGambarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/glosarium': {
      id: '/_app/admin/glosarium'
      path: '/admin/glosarium'
      fullPath: '/admin/glosarium'
      preLoaderRoute: typeof AppAdminGlosariumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/key': {
      id: '/_app/admin/key'
      path: '/admin/key'
      fullPath: '/admin/key'
      preLoaderRoute: typeof AppAdminKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/pengaturan': {
      id: '/_app/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AppAdminPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/pengguna': {
      id: '/_app/admin/pengguna'
      path: '/admin/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AppAdminPenggunaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/profil': {
      id: '/_app/admin/profil'
      path: '/admin/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AppAdminProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/referensi': {
      id: '/_app/admin/referensi'
      path: '/admin/referensi'
      fullPath: '/admin/referensi'
      preLoaderRoute: typeof AppAdminReferensiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/catatan': {
      id: '/_app/ai/catatan'
      path: '/ai/catatan'
      fullPath: '/ai/catatan'
      preLoaderRoute: typeof AppAiCatatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/chat': {
      id: '/_app/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/jelaskan': {
      id: '/_app/ai/jelaskan'
      path: '/ai/jelaskan'
      fullPath: '/ai/jelaskan'
      preLoaderRoute: typeof AppAiJelaskanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/riwayat': {
      id: '/_app/ai/riwayat'
      path: '/ai/riwayat'
      fullPath: '/ai/riwayat'
      preLoaderRoute: typeof AppAiRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/belajar/materi': {
      id: '/_app/belajar/materi'
      path: '/materi'
      fullPath: '/belajar/materi'
      preLoaderRoute: typeof AppBelajarMateriRouteImport
      parentRoute: typeof AppBelajarRoute
    }
    '/_app/kuis/$slug': {
      id: '/_app/kuis/$slug'
      path: '/$slug'
      fullPath: '/kuis/$slug'
      preLoaderRoute: typeof AppKuisSlugRouteImport
      parentRoute: typeof AppKuisRoute
    }
    '/_app/kuis/hasil': {
      id: '/_app/kuis/hasil'
      path: '/hasil'
      fullPath: '/kuis/hasil'
      preLoaderRoute: typeof AppKuisHasilRouteImport
      parentRoute: typeof AppKuisRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/kuis/': {
      id: '/_app/admin/kuis/'
      path: '/admin/kuis'
      fullPath: '/admin/kuis/'
      preLoaderRoute: typeof AppAdminKuisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/kuis/$id': {
      id: '/_app/admin/kuis/$id'
      path: '/admin/kuis/$id'
      fullPath: '/admin/kuis/$id'
      preLoaderRoute: typeof AppAdminKuisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/kuis/baru': {
      id: '/_app/admin/kuis/baru'
      path: '/admin/kuis/baru'
      fullPath: '/admin/kuis/baru'
      preLoaderRoute: typeof AppAdminKuisBaruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/materi/': {
      id: '/_app/admin/materi/'
      path: '/admin/materi'
      fullPath: '/admin/materi/'
      preLoaderRoute: typeof AppAdminMateriIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/materi/$slug': {
      id: '/_app/admin/materi/$slug'
      path: '/admin/materi/$slug'
      fullPath: '/admin/materi/$slug'
      preLoaderRoute: typeof AppAdminMateriSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/modul/': {
      id: '/_app/admin/modul/'
      path: '/admin/modul'
      fullPath: '/admin/modul/'
      preLoaderRoute: typeof AppAdminModulIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/modul/$slug': {
      id: '/_app/admin/modul/$slug'
      path: '/admin/modul/$slug'
      fullPath: '/admin/modul/$slug'
      preLoaderRoute: typeof AppAdminModulSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/modul/baru': {
      id: '/_app/admin/modul/baru'
      path: '/admin/modul/baru'
      fullPath: '/admin/modul/baru'
      preLoaderRoute: typeof AppAdminModulBaruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/prompt-studio/': {
      id: '/_app/admin/prompt-studio/'
      path: '/admin/prompt-studio'
      fullPath: '/admin/prompt-studio/'
      preLoaderRoute: typeof AppAdminPromptStudioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/prompt-studio/compiler': {
      id: '/_app/admin/prompt-studio/compiler'
      path: '/admin/prompt-studio/compiler'
      fullPath: '/admin/prompt-studio/compiler'
      preLoaderRoute: typeof AppAdminPromptStudioCompilerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/studi-kasus/': {
      id: '/_app/admin/studi-kasus/'
      path: '/admin/studi-kasus'
      fullPath: '/admin/studi-kasus/'
      preLoaderRoute: typeof AppAdminStudiKasusIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/studi-kasus/$id': {
      id: '/_app/admin/studi-kasus/$id'
      path: '/admin/studi-kasus/$id'
      fullPath: '/admin/studi-kasus/$id'
      preLoaderRoute: typeof AppAdminStudiKasusIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/studi-kasus/baru': {
      id: '/_app/admin/studi-kasus/baru'
      path: '/admin/studi-kasus/baru'
      fullPath: '/admin/studi-kasus/baru'
      preLoaderRoute: typeof AppAdminStudiKasusBaruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/chat/$id': {
      id: '/_app/ai/chat/$id'
      path: '/$id'
      fullPath: '/ai/chat/$id'
      preLoaderRoute: typeof AppAiChatIdRouteImport
      parentRoute: typeof AppAiChatRoute
    }
    '/_app/belajar/materi/$slug': {
      id: '/_app/belajar/materi/$slug'
      path: '/$slug'
      fullPath: '/belajar/materi/$slug'
      preLoaderRoute: typeof AppBelajarMateriSlugRouteImport
      parentRoute: typeof AppBelajarMateriRoute
    }
    '/_app/roadmap/materi/$slug': {
      id: '/_app/roadmap/materi/$slug'
      path: '/materi/$slug'
      fullPath: '/roadmap/materi/$slug'
      preLoaderRoute: typeof AppRoadmapMateriSlugRouteImport
      parentRoute: typeof AppRoadmapRoute
    }
    '/_app/admin/prompt-studio/engine/$id': {
      id: '/_app/admin/prompt-studio/engine/$id'
      path: '/admin/prompt-studio/engine/$id'
      fullPath: '/admin/prompt-studio/engine/$id'
      preLoaderRoute: typeof AppAdminPromptStudioEngineIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/belajar/materi/$slug/quiz': {
      id: '/_app/belajar/materi/$slug/quiz'
      path: '/quiz'
      fullPath: '/belajar/materi/$slug/quiz'
      preLoaderRoute: typeof AppBelajarMateriSlugQuizRouteImport
      parentRoute: typeof AppBelajarMateriSlugRoute
    }
  }
}

interface AppBelajarMateriSlugRouteChildren {
  AppBelajarMateriSlugQuizRoute: typeof AppBelajarMateriSlugQuizRoute
}

const AppBelajarMateriSlugRouteChildren: AppBelajarMateriSlugRouteChildren = {
  AppBelajarMateriSlugQuizRoute: AppBelajarMateriSlugQuizRoute,
}

const AppBelajarMateriSlugRouteWithChildren =
  AppBelajarMateriSlugRoute._addFileChildren(AppBelajarMateriSlugRouteChildren)

interface AppBelajarMateriRouteChildren {
  AppBelajarMateriSlugRoute: typeof AppBelajarMateriSlugRouteWithChildren
}

const AppBelajarMateriRouteChildren: AppBelajarMateriRouteChildren = {
  AppBelajarMateriSlugRoute: AppBelajarMateriSlugRouteWithChildren,
}

const AppBelajarMateriRouteWithChildren =
  AppBelajarMateriRoute._addFileChildren(AppBelajarMateriRouteChildren)

interface AppBelajarRouteChildren {
  AppBelajarMateriRoute: typeof AppBelajarMateriRouteWithChildren
}

const AppBelajarRouteChildren: AppBelajarRouteChildren = {
  AppBelajarMateriRoute: AppBelajarMateriRouteWithChildren,
}

const AppBelajarRouteWithChildren = AppBelajarRoute._addFileChildren(
  AppBelajarRouteChildren,
)

interface AppKuisRouteChildren {
  AppKuisSlugRoute: typeof AppKuisSlugRoute
  AppKuisHasilRoute: typeof AppKuisHasilRoute
}

const AppKuisRouteChildren: AppKuisRouteChildren = {
  AppKuisSlugRoute: AppKuisSlugRoute,
  AppKuisHasilRoute: AppKuisHasilRoute,
}

const AppKuisRouteWithChildren =
  AppKuisRoute._addFileChildren(AppKuisRouteChildren)

interface AppRoadmapRouteChildren {
  AppRoadmapMateriSlugRoute: typeof AppRoadmapMateriSlugRoute
}

const AppRoadmapRouteChildren: AppRoadmapRouteChildren = {
  AppRoadmapMateriSlugRoute: AppRoadmapMateriSlugRoute,
}

const AppRoadmapRouteWithChildren = AppRoadmapRoute._addFileChildren(
  AppRoadmapRouteChildren,
)

interface AppAiChatRouteChildren {
  AppAiChatIdRoute: typeof AppAiChatIdRoute
}

const AppAiChatRouteChildren: AppAiChatRouteChildren = {
  AppAiChatIdRoute: AppAiChatIdRoute,
}

const AppAiChatRouteWithChildren = AppAiChatRoute._addFileChildren(
  AppAiChatRouteChildren,
)

interface AppRouteChildren {
  AppBelajarRoute: typeof AppBelajarRouteWithChildren
  AppBerandaRoute: typeof AppBerandaRoute
  AppCariRoute: typeof AppCariRoute
  AppGambarRoute: typeof AppGambarRoute
  AppGlosariumRoute: typeof AppGlosariumRoute
  AppKalenderRoute: typeof AppKalenderRoute
  AppKartuRoute: typeof AppKartuRoute
  AppKuisRoute: typeof AppKuisRouteWithChildren
  AppMindmapRoute: typeof AppMindmapRoute
  AppNotifikasiRoute: typeof AppNotifikasiRoute
  AppPencapaianRoute: typeof AppPencapaianRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPeringkatRoute: typeof AppPeringkatRoute
  AppPomodoroRoute: typeof AppPomodoroRoute
  AppProfilRoute: typeof AppProfilRoute
  AppProgresRoute: typeof AppProgresRoute
  AppReferensiRoute: typeof AppReferensiRoute
  AppRencanaRoute: typeof AppRencanaRoute
  AppRiwayatRoute: typeof AppRiwayatRoute
  AppRoadmapRoute: typeof AppRoadmapRouteWithChildren
  AppSertifikatRoute: typeof AppSertifikatRoute
  AppSorotanRoute: typeof AppSorotanRoute
  AppStudiKasusRoute: typeof AppStudiKasusRoute
  AppTersimpanRoute: typeof AppTersimpanRoute
  AppUnduhanRoute: typeof AppUnduhanRoute
  AppVisualRoute: typeof AppVisualRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminGambarRoute: typeof AppAdminGambarRoute
  AppAdminGlosariumRoute: typeof AppAdminGlosariumRoute
  AppAdminKeyRoute: typeof AppAdminKeyRoute
  AppAdminPengaturanRoute: typeof AppAdminPengaturanRoute
  AppAdminPenggunaRoute: typeof AppAdminPenggunaRoute
  AppAdminProfilRoute: typeof AppAdminProfilRoute
  AppAdminReferensiRoute: typeof AppAdminReferensiRoute
  AppAiCatatanRoute: typeof AppAiCatatanRoute
  AppAiChatRoute: typeof AppAiChatRouteWithChildren
  AppAiJelaskanRoute: typeof AppAiJelaskanRoute
  AppAiRiwayatRoute: typeof AppAiRiwayatRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminKuisIdRoute: typeof AppAdminKuisIdRoute
  AppAdminKuisBaruRoute: typeof AppAdminKuisBaruRoute
  AppAdminMateriSlugRoute: typeof AppAdminMateriSlugRoute
  AppAdminModulSlugRoute: typeof AppAdminModulSlugRoute
  AppAdminModulBaruRoute: typeof AppAdminModulBaruRoute
  AppAdminPromptStudioCompilerRoute: typeof AppAdminPromptStudioCompilerRoute
  AppAdminStudiKasusIdRoute: typeof AppAdminStudiKasusIdRoute
  AppAdminStudiKasusBaruRoute: typeof AppAdminStudiKasusBaruRoute
  AppAdminKuisIndexRoute: typeof AppAdminKuisIndexRoute
  AppAdminMateriIndexRoute: typeof AppAdminMateriIndexRoute
  AppAdminModulIndexRoute: typeof AppAdminModulIndexRoute
  AppAdminPromptStudioIndexRoute: typeof AppAdminPromptStudioIndexRoute
  AppAdminStudiKasusIndexRoute: typeof AppAdminStudiKasusIndexRoute
  AppAdminPromptStudioEngineIdRoute: typeof AppAdminPromptStudioEngineIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBelajarRoute: AppBelajarRouteWithChildren,
  AppBerandaRoute: AppBerandaRoute,
  AppCariRoute: AppCariRoute,
  AppGambarRoute: AppGambarRoute,
  AppGlosariumRoute: AppGlosariumRoute,
  AppKalenderRoute: AppKalenderRoute,
  AppKartuRoute: AppKartuRoute,
  AppKuisRoute: AppKuisRouteWithChildren,
  AppMindmapRoute: AppMindmapRoute,
  AppNotifikasiRoute: AppNotifikasiRoute,
  AppPencapaianRoute: AppPencapaianRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPeringkatRoute: AppPeringkatRoute,
  AppPomodoroRoute: AppPomodoroRoute,
  AppProfilRoute: AppProfilRoute,
  AppProgresRoute: AppProgresRoute,
  AppReferensiRoute: AppReferensiRoute,
  AppRencanaRoute: AppRencanaRoute,
  AppRiwayatRoute: AppRiwayatRoute,
  AppRoadmapRoute: AppRoadmapRouteWithChildren,
  AppSertifikatRoute: AppSertifikatRoute,
  AppSorotanRoute: AppSorotanRoute,
  AppStudiKasusRoute: AppStudiKasusRoute,
  AppTersimpanRoute: AppTersimpanRoute,
  AppUnduhanRoute: AppUnduhanRoute,
  AppVisualRoute: AppVisualRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminGambarRoute: AppAdminGambarRoute,
  AppAdminGlosariumRoute: AppAdminGlosariumRoute,
  AppAdminKeyRoute: AppAdminKeyRoute,
  AppAdminPengaturanRoute: AppAdminPengaturanRoute,
  AppAdminPenggunaRoute: AppAdminPenggunaRoute,
  AppAdminProfilRoute: AppAdminProfilRoute,
  AppAdminReferensiRoute: AppAdminReferensiRoute,
  AppAiCatatanRoute: AppAiCatatanRoute,
  AppAiChatRoute: AppAiChatRouteWithChildren,
  AppAiJelaskanRoute: AppAiJelaskanRoute,
  AppAiRiwayatRoute: AppAiRiwayatRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminKuisIdRoute: AppAdminKuisIdRoute,
  AppAdminKuisBaruRoute: AppAdminKuisBaruRoute,
  AppAdminMateriSlugRoute: AppAdminMateriSlugRoute,
  AppAdminModulSlugRoute: AppAdminModulSlugRoute,
  AppAdminModulBaruRoute: AppAdminModulBaruRoute,
  AppAdminPromptStudioCompilerRoute: AppAdminPromptStudioCompilerRoute,
  AppAdminStudiKasusIdRoute: AppAdminStudiKasusIdRoute,
  AppAdminStudiKasusBaruRoute: AppAdminStudiKasusBaruRoute,
  AppAdminKuisIndexRoute: AppAdminKuisIndexRoute,
  AppAdminMateriIndexRoute: AppAdminMateriIndexRoute,
  AppAdminModulIndexRoute: AppAdminModulIndexRoute,
  AppAdminPromptStudioIndexRoute: AppAdminPromptStudioIndexRoute,
  AppAdminStudiKasusIndexRoute: AppAdminStudiKasusIndexRoute,
  AppAdminPromptStudioEngineIdRoute: AppAdminPromptStudioEngineIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DaftarRoute: DaftarRoute,
  ErrorServerRoute: ErrorServerRoute,
  LupaSandiRoute: LupaSandiRoute,
  MasukRoute: MasukRoute,
  PerawatanRoute: PerawatanRoute,
  ResetSandiRoute: ResetSandiRoute,
  VerifikasiEmailRoute: VerifikasiEmailRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
