/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifikasiEmailRouteImport } from './routes/verifikasi-email'
import { Route as ResetSandiRouteImport } from './routes/reset-sandi'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as LupaSandiRouteImport } from './routes/lupa-sandi'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUnduhanRouteImport } from './routes/_app.unduhan'
import { Route as AppTersimpanRouteImport } from './routes/_app.tersimpan'
import { Route as AppSorotanRouteImport } from './routes/_app.sorotan'
import { Route as AppSertifikatRouteImport } from './routes/_app.sertifikat'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppRiwayatRouteImport } from './routes/_app.riwayat'
import { Route as AppRencanaRouteImport } from './routes/_app.rencana'
import { Route as AppReferensiRouteImport } from './routes/_app.referensi'
import { Route as AppProgresRouteImport } from './routes/_app.progres'
import { Route as AppProfilRouteImport } from './routes/_app.profil'
import { Route as AppPomodoroRouteImport } from './routes/_app.pomodoro'
import { Route as AppPeringkatRouteImport } from './routes/_app.peringkat'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppPencapaianRouteImport } from './routes/_app.pencapaian'
import { Route as AppNotifikasiRouteImport } from './routes/_app.notifikasi'
import { Route as AppKuisRouteImport } from './routes/_app.kuis'
import { Route as AppKartuRouteImport } from './routes/_app.kartu'
import { Route as AppKalenderRouteImport } from './routes/_app.kalender'
import { Route as AppGlosariumRouteImport } from './routes/_app.glosarium'
import { Route as AppCariRouteImport } from './routes/_app.cari'
import { Route as AppBerandaRouteImport } from './routes/_app.beranda'
import { Route as AppBelajarRouteImport } from './routes/_app.belajar'
import { Route as AppKuisHasilRouteImport } from './routes/_app.kuis.hasil'
import { Route as AppBelajarMateriRouteImport } from './routes/_app.belajar.materi'
import { Route as AppAiChatRouteImport } from './routes/_app.ai.chat'

const VerifikasiEmailRoute = VerifikasiEmailRouteImport.update({
  id: '/verifikasi-email',
  path: '/verifikasi-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSandiRoute = ResetSandiRouteImport.update({
  id: '/reset-sandi',
  path: '/reset-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaSandiRoute = LupaSandiRouteImport.update({
  id: '/lupa-sandi',
  path: '/lupa-sandi',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUnduhanRoute = AppUnduhanRouteImport.update({
  id: '/unduhan',
  path: '/unduhan',
  getParentRoute: () => AppRoute,
} as any)
const AppTersimpanRoute = AppTersimpanRouteImport.update({
  id: '/tersimpan',
  path: '/tersimpan',
  getParentRoute: () => AppRoute,
} as any)
const AppSorotanRoute = AppSorotanRouteImport.update({
  id: '/sorotan',
  path: '/sorotan',
  getParentRoute: () => AppRoute,
} as any)
const AppSertifikatRoute = AppSertifikatRouteImport.update({
  id: '/sertifikat',
  path: '/sertifikat',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppRiwayatRoute = AppRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AppRoute,
} as any)
const AppRencanaRoute = AppRencanaRouteImport.update({
  id: '/rencana',
  path: '/rencana',
  getParentRoute: () => AppRoute,
} as any)
const AppReferensiRoute = AppReferensiRouteImport.update({
  id: '/referensi',
  path: '/referensi',
  getParentRoute: () => AppRoute,
} as any)
const AppProgresRoute = AppProgresRouteImport.update({
  id: '/progres',
  path: '/progres',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppPomodoroRoute = AppPomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => AppRoute,
} as any)
const AppPeringkatRoute = AppPeringkatRouteImport.update({
  id: '/peringkat',
  path: '/peringkat',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppPencapaianRoute = AppPencapaianRouteImport.update({
  id: '/pencapaian',
  path: '/pencapaian',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifikasiRoute = AppNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppKuisRoute = AppKuisRouteImport.update({
  id: '/kuis',
  path: '/kuis',
  getParentRoute: () => AppRoute,
} as any)
const AppKartuRoute = AppKartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => AppRoute,
} as any)
const AppKalenderRoute = AppKalenderRouteImport.update({
  id: '/kalender',
  path: '/kalender',
  getParentRoute: () => AppRoute,
} as any)
const AppGlosariumRoute = AppGlosariumRouteImport.update({
  id: '/glosarium',
  path: '/glosarium',
  getParentRoute: () => AppRoute,
} as any)
const AppCariRoute = AppCariRouteImport.update({
  id: '/cari',
  path: '/cari',
  getParentRoute: () => AppRoute,
} as any)
const AppBerandaRoute = AppBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AppRoute,
} as any)
const AppBelajarRoute = AppBelajarRouteImport.update({
  id: '/belajar',
  path: '/belajar',
  getParentRoute: () => AppRoute,
} as any)
const AppKuisHasilRoute = AppKuisHasilRouteImport.update({
  id: '/hasil',
  path: '/hasil',
  getParentRoute: () => AppKuisRoute,
} as any)
const AppBelajarMateriRoute = AppBelajarMateriRouteImport.update({
  id: '/materi',
  path: '/materi',
  getParentRoute: () => AppBelajarRoute,
} as any)
const AppAiChatRoute = AppAiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/masuk': typeof MasukRoute
  '/reset-sandi': typeof ResetSandiRoute
  '/verifikasi-email': typeof VerifikasiEmailRoute
  '/belajar': typeof AppBelajarRouteWithChildren
  '/beranda': typeof AppBerandaRoute
  '/cari': typeof AppCariRoute
  '/glosarium': typeof AppGlosariumRoute
  '/kalender': typeof AppKalenderRoute
  '/kartu': typeof AppKartuRoute
  '/kuis': typeof AppKuisRouteWithChildren
  '/notifikasi': typeof AppNotifikasiRoute
  '/pencapaian': typeof AppPencapaianRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/peringkat': typeof AppPeringkatRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profil': typeof AppProfilRoute
  '/progres': typeof AppProgresRoute
  '/referensi': typeof AppReferensiRoute
  '/rencana': typeof AppRencanaRoute
  '/riwayat': typeof AppRiwayatRoute
  '/roadmap': typeof AppRoadmapRoute
  '/sertifikat': typeof AppSertifikatRoute
  '/sorotan': typeof AppSorotanRoute
  '/tersimpan': typeof AppTersimpanRoute
  '/unduhan': typeof AppUnduhanRoute
  '/ai/chat': typeof AppAiChatRoute
  '/belajar/materi': typeof AppBelajarMateriRoute
  '/kuis/hasil': typeof AppKuisHasilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/masuk': typeof MasukRoute
  '/reset-sandi': typeof ResetSandiRoute
  '/verifikasi-email': typeof VerifikasiEmailRoute
  '/belajar': typeof AppBelajarRouteWithChildren
  '/beranda': typeof AppBerandaRoute
  '/cari': typeof AppCariRoute
  '/glosarium': typeof AppGlosariumRoute
  '/kalender': typeof AppKalenderRoute
  '/kartu': typeof AppKartuRoute
  '/kuis': typeof AppKuisRouteWithChildren
  '/notifikasi': typeof AppNotifikasiRoute
  '/pencapaian': typeof AppPencapaianRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/peringkat': typeof AppPeringkatRoute
  '/pomodoro': typeof AppPomodoroRoute
  '/profil': typeof AppProfilRoute
  '/progres': typeof AppProgresRoute
  '/referensi': typeof AppReferensiRoute
  '/rencana': typeof AppRencanaRoute
  '/riwayat': typeof AppRiwayatRoute
  '/roadmap': typeof AppRoadmapRoute
  '/sertifikat': typeof AppSertifikatRoute
  '/sorotan': typeof AppSorotanRoute
  '/tersimpan': typeof AppTersimpanRoute
  '/unduhan': typeof AppUnduhanRoute
  '/ai/chat': typeof AppAiChatRoute
  '/belajar/materi': typeof AppBelajarMateriRoute
  '/kuis/hasil': typeof AppKuisHasilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/daftar': typeof DaftarRoute
  '/lupa-sandi': typeof LupaSandiRoute
  '/masuk': typeof MasukRoute
  '/reset-sandi': typeof ResetSandiRoute
  '/verifikasi-email': typeof VerifikasiEmailRoute
  '/_app/belajar': typeof AppBelajarRouteWithChildren
  '/_app/beranda': typeof AppBerandaRoute
  '/_app/cari': typeof AppCariRoute
  '/_app/glosarium': typeof AppGlosariumRoute
  '/_app/kalender': typeof AppKalenderRoute
  '/_app/kartu': typeof AppKartuRoute
  '/_app/kuis': typeof AppKuisRouteWithChildren
  '/_app/notifikasi': typeof AppNotifikasiRoute
  '/_app/pencapaian': typeof AppPencapaianRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/peringkat': typeof AppPeringkatRoute
  '/_app/pomodoro': typeof AppPomodoroRoute
  '/_app/profil': typeof AppProfilRoute
  '/_app/progres': typeof AppProgresRoute
  '/_app/referensi': typeof AppReferensiRoute
  '/_app/rencana': typeof AppRencanaRoute
  '/_app/riwayat': typeof AppRiwayatRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/sertifikat': typeof AppSertifikatRoute
  '/_app/sorotan': typeof AppSorotanRoute
  '/_app/tersimpan': typeof AppTersimpanRoute
  '/_app/unduhan': typeof AppUnduhanRoute
  '/_app/ai/chat': typeof AppAiChatRoute
  '/_app/belajar/materi': typeof AppBelajarMateriRoute
  '/_app/kuis/hasil': typeof AppKuisHasilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/lupa-sandi'
    | '/masuk'
    | '/reset-sandi'
    | '/verifikasi-email'
    | '/belajar'
    | '/beranda'
    | '/cari'
    | '/glosarium'
    | '/kalender'
    | '/kartu'
    | '/kuis'
    | '/notifikasi'
    | '/pencapaian'
    | '/pengaturan'
    | '/peringkat'
    | '/pomodoro'
    | '/profil'
    | '/progres'
    | '/referensi'
    | '/rencana'
    | '/riwayat'
    | '/roadmap'
    | '/sertifikat'
    | '/sorotan'
    | '/tersimpan'
    | '/unduhan'
    | '/ai/chat'
    | '/belajar/materi'
    | '/kuis/hasil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/lupa-sandi'
    | '/masuk'
    | '/reset-sandi'
    | '/verifikasi-email'
    | '/belajar'
    | '/beranda'
    | '/cari'
    | '/glosarium'
    | '/kalender'
    | '/kartu'
    | '/kuis'
    | '/notifikasi'
    | '/pencapaian'
    | '/pengaturan'
    | '/peringkat'
    | '/pomodoro'
    | '/profil'
    | '/progres'
    | '/referensi'
    | '/rencana'
    | '/riwayat'
    | '/roadmap'
    | '/sertifikat'
    | '/sorotan'
    | '/tersimpan'
    | '/unduhan'
    | '/ai/chat'
    | '/belajar/materi'
    | '/kuis/hasil'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/daftar'
    | '/lupa-sandi'
    | '/masuk'
    | '/reset-sandi'
    | '/verifikasi-email'
    | '/_app/belajar'
    | '/_app/beranda'
    | '/_app/cari'
    | '/_app/glosarium'
    | '/_app/kalender'
    | '/_app/kartu'
    | '/_app/kuis'
    | '/_app/notifikasi'
    | '/_app/pencapaian'
    | '/_app/pengaturan'
    | '/_app/peringkat'
    | '/_app/pomodoro'
    | '/_app/profil'
    | '/_app/progres'
    | '/_app/referensi'
    | '/_app/rencana'
    | '/_app/riwayat'
    | '/_app/roadmap'
    | '/_app/sertifikat'
    | '/_app/sorotan'
    | '/_app/tersimpan'
    | '/_app/unduhan'
    | '/_app/ai/chat'
    | '/_app/belajar/materi'
    | '/_app/kuis/hasil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DaftarRoute: typeof DaftarRoute
  LupaSandiRoute: typeof LupaSandiRoute
  MasukRoute: typeof MasukRoute
  ResetSandiRoute: typeof ResetSandiRoute
  VerifikasiEmailRoute: typeof VerifikasiEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifikasi-email': {
      id: '/verifikasi-email'
      path: '/verifikasi-email'
      fullPath: '/verifikasi-email'
      preLoaderRoute: typeof VerifikasiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-sandi': {
      id: '/reset-sandi'
      path: '/reset-sandi'
      fullPath: '/reset-sandi'
      preLoaderRoute: typeof ResetSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-sandi': {
      id: '/lupa-sandi'
      path: '/lupa-sandi'
      fullPath: '/lupa-sandi'
      preLoaderRoute: typeof LupaSandiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/unduhan': {
      id: '/_app/unduhan'
      path: '/unduhan'
      fullPath: '/unduhan'
      preLoaderRoute: typeof AppUnduhanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tersimpan': {
      id: '/_app/tersimpan'
      path: '/tersimpan'
      fullPath: '/tersimpan'
      preLoaderRoute: typeof AppTersimpanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sorotan': {
      id: '/_app/sorotan'
      path: '/sorotan'
      fullPath: '/sorotan'
      preLoaderRoute: typeof AppSorotanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sertifikat': {
      id: '/_app/sertifikat'
      path: '/sertifikat'
      fullPath: '/sertifikat'
      preLoaderRoute: typeof AppSertifikatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/riwayat': {
      id: '/_app/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AppRiwayatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rencana': {
      id: '/_app/rencana'
      path: '/rencana'
      fullPath: '/rencana'
      preLoaderRoute: typeof AppRencanaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/referensi': {
      id: '/_app/referensi'
      path: '/referensi'
      fullPath: '/referensi'
      preLoaderRoute: typeof AppReferensiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progres': {
      id: '/_app/progres'
      path: '/progres'
      fullPath: '/progres'
      preLoaderRoute: typeof AppProgresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profil': {
      id: '/_app/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pomodoro': {
      id: '/_app/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof AppPomodoroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/peringkat': {
      id: '/_app/peringkat'
      path: '/peringkat'
      fullPath: '/peringkat'
      preLoaderRoute: typeof AppPeringkatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pencapaian': {
      id: '/_app/pencapaian'
      path: '/pencapaian'
      fullPath: '/pencapaian'
      preLoaderRoute: typeof AppPencapaianRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifikasi': {
      id: '/_app/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AppNotifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kuis': {
      id: '/_app/kuis'
      path: '/kuis'
      fullPath: '/kuis'
      preLoaderRoute: typeof AppKuisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kartu': {
      id: '/_app/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof AppKartuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kalender': {
      id: '/_app/kalender'
      path: '/kalender'
      fullPath: '/kalender'
      preLoaderRoute: typeof AppKalenderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/glosarium': {
      id: '/_app/glosarium'
      path: '/glosarium'
      fullPath: '/glosarium'
      preLoaderRoute: typeof AppGlosariumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cari': {
      id: '/_app/cari'
      path: '/cari'
      fullPath: '/cari'
      preLoaderRoute: typeof AppCariRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beranda': {
      id: '/_app/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AppBerandaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/belajar': {
      id: '/_app/belajar'
      path: '/belajar'
      fullPath: '/belajar'
      preLoaderRoute: typeof AppBelajarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kuis/hasil': {
      id: '/_app/kuis/hasil'
      path: '/hasil'
      fullPath: '/kuis/hasil'
      preLoaderRoute: typeof AppKuisHasilRouteImport
      parentRoute: typeof AppKuisRoute
    }
    '/_app/belajar/materi': {
      id: '/_app/belajar/materi'
      path: '/materi'
      fullPath: '/belajar/materi'
      preLoaderRoute: typeof AppBelajarMateriRouteImport
      parentRoute: typeof AppBelajarRoute
    }
    '/_app/ai/chat': {
      id: '/_app/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AppAiChatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppBelajarRouteChildren {
  AppBelajarMateriRoute: typeof AppBelajarMateriRoute
}

const AppBelajarRouteChildren: AppBelajarRouteChildren = {
  AppBelajarMateriRoute: AppBelajarMateriRoute,
}

const AppBelajarRouteWithChildren = AppBelajarRoute._addFileChildren(
  AppBelajarRouteChildren,
)

interface AppKuisRouteChildren {
  AppKuisHasilRoute: typeof AppKuisHasilRoute
}

const AppKuisRouteChildren: AppKuisRouteChildren = {
  AppKuisHasilRoute: AppKuisHasilRoute,
}

const AppKuisRouteWithChildren =
  AppKuisRoute._addFileChildren(AppKuisRouteChildren)

interface AppRouteChildren {
  AppBelajarRoute: typeof AppBelajarRouteWithChildren
  AppBerandaRoute: typeof AppBerandaRoute
  AppCariRoute: typeof AppCariRoute
  AppGlosariumRoute: typeof AppGlosariumRoute
  AppKalenderRoute: typeof AppKalenderRoute
  AppKartuRoute: typeof AppKartuRoute
  AppKuisRoute: typeof AppKuisRouteWithChildren
  AppNotifikasiRoute: typeof AppNotifikasiRoute
  AppPencapaianRoute: typeof AppPencapaianRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppPeringkatRoute: typeof AppPeringkatRoute
  AppPomodoroRoute: typeof AppPomodoroRoute
  AppProfilRoute: typeof AppProfilRoute
  AppProgresRoute: typeof AppProgresRoute
  AppReferensiRoute: typeof AppReferensiRoute
  AppRencanaRoute: typeof AppRencanaRoute
  AppRiwayatRoute: typeof AppRiwayatRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSertifikatRoute: typeof AppSertifikatRoute
  AppSorotanRoute: typeof AppSorotanRoute
  AppTersimpanRoute: typeof AppTersimpanRoute
  AppUnduhanRoute: typeof AppUnduhanRoute
  AppAiChatRoute: typeof AppAiChatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBelajarRoute: AppBelajarRouteWithChildren,
  AppBerandaRoute: AppBerandaRoute,
  AppCariRoute: AppCariRoute,
  AppGlosariumRoute: AppGlosariumRoute,
  AppKalenderRoute: AppKalenderRoute,
  AppKartuRoute: AppKartuRoute,
  AppKuisRoute: AppKuisRouteWithChildren,
  AppNotifikasiRoute: AppNotifikasiRoute,
  AppPencapaianRoute: AppPencapaianRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppPeringkatRoute: AppPeringkatRoute,
  AppPomodoroRoute: AppPomodoroRoute,
  AppProfilRoute: AppProfilRoute,
  AppProgresRoute: AppProgresRoute,
  AppReferensiRoute: AppReferensiRoute,
  AppRencanaRoute: AppRencanaRoute,
  AppRiwayatRoute: AppRiwayatRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSertifikatRoute: AppSertifikatRoute,
  AppSorotanRoute: AppSorotanRoute,
  AppTersimpanRoute: AppTersimpanRoute,
  AppUnduhanRoute: AppUnduhanRoute,
  AppAiChatRoute: AppAiChatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DaftarRoute: DaftarRoute,
  LupaSandiRoute: LupaSandiRoute,
  MasukRoute: MasukRoute,
  ResetSandiRoute: ResetSandiRoute,
  VerifikasiEmailRoute: VerifikasiEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
